# Make sure terminal colors work with kitty
set-option -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"

# reduce lag
set-option -s escape-time 0

# enable clipboard passthrough (osc52) - Out only
set -s set-clipboard on
set -g allow-passthrough on

# vi keys for navigating in copy mode
set-option -g mode-keys vi

# Allow mouse scrolling
set -g mouse on

# For neovim 'autoread' recommended by :checkhealth
set-option -g focus-events on

bind-key -r r source ~/.tmux.conf \; display-message "Config reloaded"
bind-key -r ^ last-window
# To move between panes
bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r h select-pane -L
bind-key -r l select-pane -R

# To move panes
bind-key -r C-j select-pane -D \; swap-pane -d -s '!' 
bind-key -r C-k select-pane -U \; swap-pane -d -s '!' 
bind-key -r C-h select-pane -L \; swap-pane -d -s '!' 
bind-key -r C-l select-pane -R \; swap-pane -d -s '!' 

# To resize panes
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r H resize-pane -L 5
bind-key -r L resize-pane -R 5

# Long history
set -g history-limit 100000

# Investigate further
#set-window-option -g xterm-keys on

# To copy between panes
# 1. enter copy mode, Ctrl-b - [
# 2. move cursor to start of text
# 3. Begin highlighting, Space 
# 4. move cursor to end of text
# 5. Copy text to tmux buffer, Enter
# 6. move to desired pane for pasting text
# 7. move cursor to start of paste location
# 8. paste the text, Ctrl-b - ] 

# To copy to OS when running via SSH 
# 1. Full screen pane
# 2. Use Shift + Left Mouse to select text
# 3. Command-C to copy to OS buffer
# 4. Commadn-V to copy from OS buffer to whatever you are pasting into.
